blog/apps/Comentarios/urls.py
from django.urls import path
from . import views

app_name = "comentarios"

urlpatterns = [
    path("agergar/<int:pk>", views.Agregar_Comentario, name="agregar"),
    path("borrar/<int:pk>", views.BorrarComentario.as_view(), name="borrar_comentario"),
    path(
        "modificar/<int:pk>",
        views.ModificaComentario.as_view(),
        name="modificar_comentario",
    ),
]

blog/apps/Post/urls.py
from django.urls import path
from . import views

app_name = "noticias"

urlpatterns = [
    path("", views.Home_Noticias, name="home_noticias"),
    path("cargar/", views.Cargar_noticia.as_view(), name="cargar_noticia"),
    path("Detalle/<int:pk>", views.Detalle_noticia, name="detalle_noticia"),
    path(
        "Modificar/<int:pk>",
        views.Modificar_noticia.as_view(),
        name="modificar_noticia",
    ),
    path("Borrar/<int:pk>", views.Borrar_noticia.as_view(), name="borrar_noticia"),
    path("likes/<int:pk>", views.megusta, name="megusta"),
]

blog/apps/Users/urls.py
from django.urls import path
from . import views

app_name = "usuarios"

urlpatterns = [
    path("Registro/", views.Registro.as_view(), name="registro_usuario"),
    path("<str:username>/", views.Ver_perfil, name="ver_perfil"),
    path(
        "Modificar/<int:pk>/",
        views.Modificar_usuario.as_view(),
        name="modificar_perfil",
    ),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.Home, name="Inicio"),
    path("contactos/", include("apps.contactos.urls"), name="Contacto"),
    # APP NOTICIAS
    path("Post/", include("apps.Post.urls")),
    # LOGIN Y LOGOUT
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="Users/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "reset_password/",
        views.CustomPasswordResetView.as_view(
            template_name="Users/Acceso/password_reset.html"
        ),
        name="password_reset",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="Users/Acceso/password_reset_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="Users/Acceso/password_reset_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="Users/Acceso/password_reset_done.html"
        ),
        name="password_reset_complete",
    ),
    # APP USUARIOs
    path("Users/", include("apps.Users.urls")),
    # APP Comentarios
    path("Comentarios/", include("apps.Comentarios.urls")),
    path("acercade/", views.Acercade, name="acercade"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/Post/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.conf import settings

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Noticia(models.Model):
    creado = models.DateTimeField("creado", auto_now_add=True)
    modificado = models.DateTimeField("modificado", auto_now=True)
    titulo = models.CharField(max_length=250)
    contenido = RichTextField()
    imagen = models.ImageField(upload_to="noticias")
    categorias = models.ManyToManyField(Categoria)
    visitas = models.PositiveIntegerField(default=0)
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="not_megustas", blank=True
    )
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False, null=False
    )

    def count_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.titulo
 
    class Meta:
        permissions = [
            ('can_manage_noticias', 'can manage noticias'),
            ('can_manage_comentarios', 'Can manage comentarios'),
        ]

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

blog/apps/Post/forms.py
from django import forms
from .models import Noticia, Categoria


class Formulario_Noticia(forms.ModelForm):
    categorias = forms.ModelMultipleChoiceField(
        queryset=Categoria.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )
    class Meta:
        model = Noticia
        fields = ["titulo", "contenido", "imagen", "categorias"]
        widgets = {
            "titulo": forms.TextInput(attrs={"class": "form-control"}),
            "contenido": forms.Textarea(attrs={"class": "form-control"}),
            "imagen": forms.FileInput(attrs={"class": "form-control"}),
        }



class Formulario_Modificar_Noticia(forms.ModelForm):
    categorias = forms.ModelMultipleChoiceField(
        queryset=Categoria.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )
    class Meta:
        model = Noticia
        fields = ["titulo", "contenido", "imagen", "categorias"]
        widgets = {
            "titulo": forms.TextInput(attrs={"class": "form-control"}),
            "contenido": forms.Textarea(attrs={"class": "form-control"}),
            "imagen": forms.FileInput(attrs={"class": "form-control"}),
        }

blog/apps/Post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from .models import Noticia, Categoria
from .forms import Formulario_Noticia, Formulario_Modificar_Noticia
from apps.Comentarios.models import Comentario


def Home_Noticias(request):
    contexto = {}

    contexto["categorias"] = Categoria.objects.all()

    filtro = request.GET.get("categoria", "0")
    orden = request.GET.get("orden", "-creado")
    busqueda = request.GET.get("q", "")

    todas = Noticia.objects.all()

    if filtro and filtro != "0":
        todas = todas.filter(categorias__id=filtro)

    if busqueda:
        todas = todas.filter(titulo__icontains=busqueda) | todas.filter(
            contenido__icontains=busqueda
        )

    # Ordenar las noticias
    if orden == "titulo_asc":
        todas = todas.order_by("titulo")
    elif orden == "titulo_desc":
        todas = todas.order_by("-titulo")
    elif orden == "creado_asc":
        todas = todas.order_by("creado")
    else:  # Default to descending creation date
        todas = todas.order_by("-creado")

    paginator = Paginator(todas, 5)
    page = request.GET.get("page")

    try:
        noticias = paginator.page(page)
    except PageNotAnInteger:
        noticias = paginator.page(1)
    except EmptyPage:
        noticias = paginator.page(paginator.num_pages)

    contexto["noticias_populares"] = Noticia.objects.order_by("-visitas")[:3]
    contexto["noticias"] = noticias

    return render(request, "Post/inicio_post.html", contexto)

class Cargar_noticia(LoginRequiredMixin, CreateView):
    model = Noticia
    template_name = "Post/load_post.html"
    form_class = Formulario_Noticia
    success_url = reverse_lazy("Post:home_post")

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)


class Modificar_noticia(LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin, UpdateView):
    model = Noticia
    template_name = "Post/modifications_post.html"
    form_class = Formulario_Modificar_Noticia
    success_url = reverse_lazy("Post:home_post")
    permission_required = 'Post.change_post'

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)

    def test_func(self):
        noticia = self.get_object()
        return self.request.user == noticia.usuario or self.request.user.groups.filter(name='colaborador').exists()

    def handle_no_permission(self):
        noticia = self.get_object()
        return redirect("Post:detalle_post", pk=noticia.pk)

    def has_permission(self):
        # Permitir a los colaboradores editar cualquier noticia
        return self.request.user.has_perm('Post.change_post')

class Borrar_noticia(PermissionRequiredMixin, DeleteView):
    model = Noticia
    permission_required = 'Post.delete_post'

    def get_success_url(self):
        return reverse_lazy("Post:home_post")
        
    def delete(self, request, *args, **kwargs):
        noticia = self.get_object()
        if request.user == noticia.usuario or request.user.groups.filter(name='colaborador').exists():
            
            return super().delete(request, *args, **kwargs)
        else:
            
            return HttpResponseRedirect(self.get_success_url())
    
    def has_permission(self):
        # Permitir a los colaboradores eliminar cualquier noticia
        return self.request.user.has_perm('Post.delete_post')



def Detalle_noticia(request, pk):
    ctx = {}
    noticia = get_object_or_404(Noticia, pk=pk)

    noticia.visitas += 1
    noticia.save()

    ctx["likes"] = noticia.count_likes()
    ctx["noticia"] = noticia
    ctx["checklike"] = request.user in noticia.likes.all()
    com = Comentario.objects.filter(noticia=noticia)
    ctx["comentarios"] = com
    return render(request, "Post/info_post.html", ctx)


def megusta(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)
    if request.user in noticia.likes.all():
        noticia.likes.remove(request.user)
    else:
        noticia.likes.add(request.user.id)
    return redirect("/Post/Detalle/" + str(noticia.id))

blog/templates/Posts/info_post.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}

{% block contenido %}
  <header class="mosthead w-100 img-fluid position-relative" style="background-image: url('{{ noticia.imagen.url }}'); object-fit: cover;">
    <div class="overlay"></div>
    <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="post-heading text-center">
            <h1 class="fw-bolder text-center" style="color: rgb(243, 243, 243);">{{ noticia.titulo }}</h1>
          </div>
        </div>
      </div>
    </div>
  </header>
  <article class="mb-4">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <p>{{ noticia.contenido|safe }}</p>
          <span class="meta">
            Publicado por
            <a class="text-decoration-none" href="{% url 'usuarios:ver_perfil' noticia.usuario %}"><strong>{{ noticia.usuario }}</strong></a>

            el {{ noticia.creado }} - <a href="{% url 'noticias:megusta' noticia.pk %}" class="text-decoration-none">
              {% if checklike %}
                <i class="fa fa-heart"></i>
              {% else %}
                <i class="fa fa-heart-o"></i>
              {% endif %}
            </a>
            {{ likes }}
          </span>
          {% if request.user.is_authenticated %}
            {% if user.id == noticia.usuario.pk or user|is_colab %}
              <form method="post" action="{% url 'noticias:borrar_noticia' noticia.pk %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="text-decoration-none text-danger border-0 bg-transparent" onclick="return confirmarEliminarNoticia()">Eliminar</button>
              </form>
              <a class="text-decoration-none text-danger" href="{% url 'noticias:modificar_noticia' noticia.pk %}">Editar</a>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </article>
  <hr />
  <section class="mb-5">
    <div class="card bg-light">
      <div class="card-body">
        {% for comentario in comentarios %}
          <div class="d-flex mb-4">
            <div class="flex-shrink-0">
              <img class="rounded-circle" src="{{ comentario.usuario.picture.url }}" alt="Imagen de perfil" width="50" height="50" style="margin-right: 5px;" />
            </div>
            <div class="ms-3">
              <div class="fw-bold">{{ comentario.usuario.username }}</div>
              {{ comentario.contenido }}
              <div class="mt-2">
                <small>Publicado hace {{ comentario.fecha_creacion|timesince }}</small>

                {% if user.is_authenticated %}
                  {% if user.id == comentario.usuario.pk or user|is_colab %}
                    <form method="post" action="{% url 'comentarios:borrar_comentario' comentario.pk %}" style="display: inline;">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-link text-danger text-decoration-none" onclick="return confirmarEliminarComentario()">Eliminar</button>
                    </form>
                  {% endif %}
                  {% if user.id == comentario.usuario.pk %}
                    <a class="btn btn-link text-danger text-decoration-none" href="{% url 'comentarios:modificar_comentario' comentario.pk %}">Editar</a>
                  {% endif %}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
        {% if user.is_authenticated %}
          <form method="POST" action="{% url 'comentarios:agregar' noticia.pk %}" class="mb-4">
            {% csrf_token %}
            <textarea name="comentario" class="form-control" rows="3" placeholder="Deja tu comentario"></textarea>
            <button type="submit" class="btn btn-primary mt-3">Comentar</button>
          </form>
        {% else %}
          <p>Debes estar registrado para dejar un comentario.</p>
          <a href="{% url 'login' %}" class="btn btn-primary">Iniciar sesión</a>
        {% endif %}
      </div>
    </div>
  </section>
{% endblock %}

blog/templates/Posts/inicio_post.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<header class="text-center text-white py-2">
  <div id="carouselExampleCaptions" class="carousel slide" style="max-width: 100%; margin: auto;">
    <div class="carousel-indicators">
      {% for i in noticias_populares %}
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{ forloop.counter0 }}" {%if forloop.first %} class="active" {% endif %} aria-label="Slide {{ forloop.counter }}">
      </button>
      {% endfor %}
    </div>
    <div class="carousel-inner">
      {% for n in noticias_populares %}
      <div class="carousel-item {% if forloop.first %}active{% endif %}">
        <img src="{{ n.imagen.url }}" class="d-block img-fluid" style="width: 100%; height: 720px; object-fit: cover;">
        <div class="carousel-caption d-none d-md-block">
          <h5 class="fw-bolder">{{ n.titulo }}</h5>
        </div>
      </div>
      {% endfor %}
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</header>

<div class="container">
  <div class="row">
    <!-- Blog entries-->
    <div class="col-lg-8">
          <!-- Ordenar noticias -->
      <div class="mb-4">
        <form method="get" action="{% url 'noticias:home_noticias' %}">
          <div class="input-group">
            <select class="form-select" name="orden">
              <option value="-creado" {% if request.GET.orden == "-creado" %}selected{% endif %}>Más recientes</option>
              <option value="creado_asc" {% if request.GET.orden == "creado_asc" %}selected{% endif %}>Más antiguas</option>
              <option value="titulo_asc" {% if request.GET.orden == "titulo_asc" %}selected{% endif %}>Título A-Z</option>
              <option value="titulo_desc" {% if request.GET.orden == "titulo_desc" %}selected{% endif %}>Título Z-A</option>
            </select>
            <button class="btn btn-primary" type="submit">Ordenar</button>
          </div>
        </form>
      </div>
      <!-- Featured blog post-->
      {% if noticias %}
      <div class="card mb-4">
        <a href="{% url 'noticias:detalle_noticia' noticias.0.pk %}"><img class="card-img-top"
            style="width: 100%; height: 350px" src="{{ noticias.0.imagen.url }}" /></a>
        <div class="card-body">
          <div class="small text-muted">{{ noticias.0.creado }}--
          {% for categoria in noticias.0.categorias.all %}
              {{ categoria.nombre }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </div>
          <h2 class="card-title">{{ noticias.0.titulo }}</h2>
          <p class="card-text">{{ noticias.0.contenido|striptags|truncatechars:100 }}</p>

          <a class="btn btn-primary border shadow gradient-custom-2 mb-3"
            href="{% url 'noticias:detalle_noticia' noticias.0.pk %}">Leer más</a>
        </div>
      </div>
      <hr>
      {% endif %}
      <div class="row">
        {% for n in noticias|slice:"1:5" %}
        <div class="col-lg-6">

          <div class="card mb-4">
            <a href="{% url 'noticias:detalle_noticia' n.pk %}"><img class="card-img-top" src="{{ n.imagen.url }}"
                style="width: 100%; height: 350px" /></a>
            <div class="card-body">
              <div class="small text-muted">{{ n.creado }}--
              {% for categoria in n.categorias.all %}
                  {{ categoria.nombre }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
                </div>
              <h2 class="card-title h4">{{ n.titulo }}</h2>
              <p class="card-text">{{ n.contenido|striptags|linebreaksbr|truncatechars:100|safe }}</p>
              <a class="btn btn-primary border shadow gradient-custom-2 mb-3"
                href="{% url 'noticias:detalle_noticia' n.pk %}">Leer más</a>
            </div>
          </div>

        </div>
        {% endfor %}
      </div>
      <!-- Pagination-->
      <nav aria-label="Pagination">
        <hr class="my-0" />
        <ul class="pagination justify-content-center my-4">
          {% if noticias.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">Anterior</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ noticias.previous_page_number }}">Previa</a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <span class="page-link">Inicio</span>
          </li>
          {% endif %}

          {% for num in noticias.paginator.page_range %}
          {% if noticias.number == num %}
          <li class="page-item active" aria-current="page">
            <span class="page-link">{{ num }}</span>
          </li>
          {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
          {% endif %}
          {% endfor %}

          {% if noticias.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ noticias.next_page_number }}">Siguiente</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ noticias.paginator.num_pages }}">Ultima</a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <span class="page-link">Ultima</span>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
    <div class="col-lg-4">
      <div class="card mb-4">
        <div class="card-header">Buscar Noticia</div>
        <div class="card-body">
          <form method="get" action="{% url 'noticias:home_noticias' %}">
            <div class="input-group">
              <input class="form-control" type="text" name="q" placeholder="Enter search term..."
                aria-label="Enter search term..." aria-describedby="button-search" />
              <button class="btn btn-primary" id="button-search" type="submit">Buscar</button>
            </div>
          </form>
        </div>
      </div>
      <div class="card mb-4">
        <div class="card-header">Categorias</div>
        <div class="card-body">
          <div class="row">
            <div class="col-sm-6">
              <ul class="list-unstyled mb-0">
                <li><a class="text-decoration-none" href="?categoria=0"><strong>TODAS</strong></a></li>
                {% for c in categorias|slice:":2" %}
                <li><a class="text-decoration-none" href="?categoria={{c.id}}"><strong>{{c.nombre}}</strong></a></li>
                {% endfor %}
              </ul>
            </div>
            <div class="col-sm-6">
              <ul class="list-unstyled mb-0">
                {% for c in categorias|slice:"2:" %}
                <li><a class="text-decoration-none" href="?categoria={{c.id}}"><strong>{{c.nombre}}</strong></a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      {% if user.is_authenticated %}
      <div class="card mb-4">
        <div class="card-header {% if request.path == url %}active{% endif %} text-center"><a class="nav-link"
            href="{% url 'noticias:cargar_noticia' %}">Publicar Noticia</a></div>
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock contenido %}

blog/templates/Posts/load_post.html
{% extends 'base.html' %} 
{% block contenido %}
  <div class="mx-auto text-center">
    <h3>CREAR NOTICIA</h3>
    {% if user.is_authenticated %}
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form.media }} 
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mb-4">Confirmar</button>
      </form>
    {% else %}
      <h3>Incia sesion o registrate para postear!</h3>
    {% endif %}
  </div>
{% endblock %}

blog/templates/Posts/modifications_post.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block contenido %}
  <div class="mx-auto text-center">
    <h2>Modificar Noticia</h2>
    {% if user.is_authenticated %}
      {% if user.id == noticia.usuario.pk or user|is_colab %}
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.media }}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
      {% endif %}
    {% endif %}
  </div>
{% endblock %}