blog/apps/Post/urls.py
from django.urls import path
from . import views

app_name = "noticias"

urlpatterns = [
    path("", views.Home_Noticias, name="home_noticias"),
    path("cargar/", views.Cargar_noticia.as_view(), name="cargar_noticia"),
    path("Detalle/<int:pk>", views.Detalle_noticia, name="detalle_noticia"),
    path(
        "Modificar/<int:pk>",
        views.Modificar_noticia.as_view(),
        name="modificar_noticia",
    ),
    path("Borrar/<int:pk>", views.Borrar_noticia.as_view(), name="borrar_noticia"),
    path("likes/<int:pk>", views.megusta, name="megusta"),
]

blog/apps/Users/urls.py
from django.urls import path
from . import views

app_name = "usuarios"

urlpatterns = [
    path("Registro/", views.Registro.as_view(), name="registro_usuario"),
    path("<str:username>/", views.Ver_perfil, name="ver_perfil"),
    path(
        "Modificar/<int:pk>/",
        views.Modificar_usuario.as_view(),
        name="modificar_perfil",
    ),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.Home, name="Inicio"),
    path("contactos/", include("apps.contactos.urls"), name="Contacto"),
    # APP NOTICIAS
    path("Post/", include("apps.Post.urls")),
    # LOGIN Y LOGOUT
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="Users/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "reset_password/",
        views.CustomPasswordResetView.as_view(
            template_name="Users/Acceso/password_reset.html"
        ),
        name="password_reset",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="Users/Acceso/password_reset_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="Users/Acceso/password_reset_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="Users/Acceso/password_reset_done.html"
        ),
        name="password_reset_complete",
    ),
    # APP USUARIOs
    path("Users/", include("apps.Users.urls")),
    # APP Comentarios
    path("Comentarios/", include("apps.Comentarios.urls")),
    path("acercade/", views.Acercade, name="acercade"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/templates/components/footer.html
{% load static%}
<!-- Footer -->

    <footer class="text-center text-lg-start bg-body-tertiary text-muted footer ">
        <div class="position-static p-2">
            <section class="d-flex justify-content-center justify-content-lg-between ">
                <div class="container px-4 px-lg-5">
                    <div class="row gx-4 gx-lg-5 justify-content-center">
                        <div class="col-md-10 col-lg-8 col-xl-7">
                            <ul class="list-inline text-center">
                                <li class="list-inline-item">
                                    <a href="https://github.com/MatiasAFernandez/Informatorio_Blog_Django">
                                        <span class="fa-stack fa-lg">
                                            <i class="fas fa-circle fa-stack-2x"></i>
                                            <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                        </span>
                                    </a>
                                </li>
                            </ul>
                            <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2024</div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </footer>

<!-- Footer -->

blog/templates/components/navegacion.html
{% load static%}

<nav class="navbar fw-bolder navbar-expand-lg bg-body-tertiary fixed-top nav-underline ">
    <div class="container-fluid">
        <a class="navbar-brand ps-1" href="{% url 'Inicio' %}">
            <img src="{% static 'img/icono.ico' %}" alt="Logo" /> 
            Racing News
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto justify-content-center pe-5">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="{% url 'Inicio' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/noticias/' %}active{% endif %}"
                        href="{% url 'noticias:home_noticias' %}">Noticias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/contacto/' %}active{% endif %}"
                        href="{% url 'contacto:cargar_contacto' %}">Contacto</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link {% if request.path == '/acercade/' %}active{% endif %}"
                        href="{% url 'acercade' %}">Acerca de</a>
                </li>
            </ul>

            <ul class="navbar-nav pe-5">
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown pe-5">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        
                        <img src="{{request.user.picture.url}}" alt="Imagen de perfil" class="rounded-circle" width="35" height="35" style="margin-right: 5px;">
                        {{request.user.username}}
                    </a>
                    <ul class="dropdown-menu " aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{%url "usuarios:ver_perfil" request.user.username%}">Ver perfil</a></li>
                      <li><a class="dropdown-item" href="{% url 'usuarios:modificar_perfil' request.user.pk %}">Modificar perfil</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#"><form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary border shadow gradient-custom-2 d-sm-block">
                            Cerrar sesión
                        </button>
                    </form></a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'login'%}" class="btn btn-primary border shadow gradient-custom-2 d-sm-block">
                        Inicia Sesión
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>