blog/apps/Post/urls.py
from django.urls import path
from . import views

app_name = "noticias"

urlpatterns = [
    path("", views.Home_Noticias, name="home_noticias"),
    path("cargar/", views.Cargar_noticia.as_view(), name="cargar_noticia"),
    path("Detalle/<int:pk>", views.Detalle_noticia, name="detalle_noticia"),
    path(
        "Modificar/<int:pk>",
        views.Modificar_noticia.as_view(),
        name="modificar_noticia",
    ),
    path("Borrar/<int:pk>", views.Borrar_noticia.as_view(), name="borrar_noticia"),
    path("likes/<int:pk>", views.megusta, name="megusta"),
]

blog/apps/Users/urls.py
from django.urls import path
from . import views

app_name = "usuarios"

urlpatterns = [
    path("Registro/", views.Registro.as_view(), name="registro_usuario"),
    path("<str:username>/", views.Ver_perfil, name="ver_perfil"),
    path(
        "Modificar/<int:pk>/",
        views.Modificar_usuario.as_view(),
        name="modificar_perfil",
    ),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.Home, name="Inicio"),
    path("contactos/", include("apps.contactos.urls"), name="Contacto"),
    # APP NOTICIAS
    path("Post/", include("apps.Post.urls")),
    # LOGIN Y LOGOUT
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="Users/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "reset_password/",
        views.CustomPasswordResetView.as_view(
            template_name="Users/Acceso/password_reset.html"
        ),
        name="password_reset",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="Users/Acceso/password_reset_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="Users/Acceso/password_reset_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="Users/Acceso/password_reset_done.html"
        ),
        name="password_reset_complete",
    ),
    # APP USUARIOs
    path("Users/", include("apps.Users.urls")),
    # APP Comentarios
    path("Comentarios/", include("apps.Comentarios.urls")),
    path("acercade/", views.Acercade, name="acercade"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/Users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    picture = models.ImageField(upload_to="Users/", default="Users/default.webp")
    bio = models.CharField(max_length=150, blank=True)
    is_colab = models.BooleanField(default=False)

    def __str__(self):
        return self.username
    

blog/apps/Users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from apps.Users.models import CustomUser


class RegistroForm(UserCreationForm):
    first_name = forms.CharField(
        label="Nombre",
        max_length=30,
        widget=forms.TextInput(
            attrs={"placeholder": "Ingrese su nombre", "class": "form-control"}
        ),
    )

    last_name = forms.CharField(
        label="Apellido",
        max_length=30,
        widget=forms.TextInput(
            attrs={"placeholder": "Ingrese su apellido", "class": "form-control"}
        ),
    )

    username = forms.CharField(
        label="Nombre de usuario",
        max_length=30,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Ingrese su nombre de usuario",
                "class": "form-control",
            }
        ),
    )

    email = forms.EmailField(
        label="Correo electrónico",
        max_length=254,
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Ingrese su correo electrónico",
                "class": "form-control",
            }
        ),
    )

    password1 = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(
            attrs={"placeholder": "Ingrese su contraseña", "class": "form-control"}
        ),
    )

    password2 = forms.CharField(
        label="Confirmar contraseña",
        widget=forms.PasswordInput(
            attrs={"placeholder": "Confirme su contraseña", "class": "form-control"}
        ),
    )

    class Meta:
        model = CustomUser
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        ]


class Formulario_Modificar_Usuario(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "username", "email", "picture", "bio"]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control p-2 m-2'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control p-2 m-2'}),
            'username': forms.TextInput(attrs={'class': 'form-control p-2 m-2'}),
            'email': forms.EmailInput(attrs={'class': 'form-control p-2 m-2'}),
            'picture': forms.ClearableFileInput(attrs={'class': 'form-control-file p-2 m-2'}),
            'bio': forms.Textarea(attrs={'class': 'form-control p-2 m-2'}),
        }

blog/apps/Users/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, UpdateView
from django.urls import reverse_lazy
from apps.Post.models import Noticia
from apps.Comentarios.models import Comentario
from .forms import RegistroForm, Formulario_Modificar_Usuario
from .models import CustomUser


def Ver_perfil(request, username):
    ctx = {}
    user = get_object_or_404(CustomUser, username=username)
    noticias_user = Noticia.objects.filter(usuario=user)
    comentarios_user = Comentario.objects.filter(usuario=user)
    ctx["noticias_user"] = noticias_user
    ctx["user"] = user
    ctx["comentarios_user"] = comentarios_user
    return render(request, "Users/profile.html", ctx)


class Registro(CreateView):
    form_class = RegistroForm
    success_url = reverse_lazy("login")
    template_name = "Users/Acceso/registro.html"


class Modificar_usuario(UpdateView):
    model = CustomUser
    template_name = "Users/change_profile.html"
    form_class = Formulario_Modificar_Usuario

    def get_success_url(self):
        username = self.object.username
        return reverse_lazy("usuarios:ver_perfil", kwargs={"username": username})

blog/templates/Users/change_profile.html
{% extends 'base.html' %} {% load static %} {% block contenido %}
<div class="mx-auto text-center">
<h3>MODIFICAR PERFIL</h3>
  
  {% if request.user.is_authenticated %}
    {%if request.user.id ==  object.id%}
      <form method="post" enctype="multipart/form-data" >
        {% csrf_token %} {{ form.as_p }}
        <button type="submit" class="btn btn-primary mb-4">Confirmar</button>
      </form>
      {% else %}
      <h1>usuario incorrecto</h1>
      {% endif %}
      {% endif %}
    </div>
{% endblock %}

blog/templates/Users/login.html
{% extends 'base.html' %} {% load static %} {% block contenido %}
  <form method="POST">
    {% csrf_token %}
    <section class="h-100 gradient-form" style="background-color: #eee">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-xl-10">
            <div class="card rounded-3 text-black">
              <div class="row g-0">
                <div class="col-lg-6">
                  <div class="card-body p-md-5 mx-md-4">
                    <div class="text-center">
                      <img src="{% static 'img/icono2.png' %}" style="width: 120px" alt="logo" />                    
                    </div>

                    <p>Por favor, inicie sesión</p>

                    <div class="form-outline mb-4">
                      <label for="{{ form.username.usuario }}">Usuario</label>
                      <input type="text" class="form-control" id="{{ form.username.id }}" name="username" placeholder="Usuario" />
                      {{ form.username.errors }}
                    </div>
                    <div class="form-outline mb-4">
                      <label for="{{ form.contrasena.usuario }}">Contraseña</label>
                      <input type="password" class="form-control" id="{{ form.contrasena.id }}" name="password" placeholder="Contraseña" />
                      {{ form.contrasena.errors }}
                    </div>
                    {% if form.non_field_errors %}
                      <div class="form-outline mb-4">
                        {% for error in form.non_field_errors %}
                          <strong class="text-danger">{{ error|escape }}</strong>
                        {% endfor %}
                      </div>
                    {% endif %}

                    <div class="text-center pt-1 mb-5 pb-1 d-grid gap-2">
                      <button class="btn btn-primary border shadow gradient-custom-2 mb-3" value="ENVIAR" type="submit">Iniciar Sesión</button>
                      <a class="text-muted" href="{% url 'password_reset' %}">Recuperar contraseña</a>
                    </div>

                    <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2">No tienes una cuenta?</p>
                      <a type="button" class="btn shadow btn-outline-danger opacity-60" href="{% url 'usuarios:registro_usuario' %}">Registrate</a>
                    </div>
                    <div class="d-flex justify-content-center">                     
                       <a class=" text-muted" href="{%url 'Inicio'%}">Volver al inicio</a>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                  <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                    <h4 class="mb-4">Bienvenido a Racing News: Tu dosis de velocidad</h4>
                    <p class="small mb-0">¡Hola, amante del automovilismo! En Racing News, nos apasiona proporcionarte las últimas noticias e información sobre esas maquinas de cuatro ruadas que tanto nos encantan.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </form>
{% endblock %}

blog/templates/Users/profile.html
{% extends 'base.html' %} {%load static%} {% block contenido %}

<body class="bg-light">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <div class="text-center">
                            <img src="{{ user.picture.url }}" alt="Imagen de Perfil" class="rounded-circle img-fluid" style="max-width: 150px; max-height: 150px;object-fit: cover;">
                            <h2 class="mt-3">Nombre: {{ user.first_name }} {{ user.last_name }}</h2>
                            <p class="fw-bold">Usuario: {{ user.username }}</p>
                            <p>Bio: {{ user.bio }}</p>
                        </div>
                        
                        <ul class="nav nav-tabs mt-4">
                            <li class="nav-item">
                                <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts">Posts({{noticias_user|length}})</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="comments-tab" data-toggle="tab" href="#comments">Comentarios({{comentarios_user|length}})</a>
                            </li>
                        </ul>
                        
                        <div class="tab-content mt-3">
                            <div class="tab-pane fade show active" id="posts">
                                <!-- Contenido de la pestaña de posts -->
                                
                                {% for n in noticias_user %}
                                    <div class="card mb-3">
                                        <div class="card-body">
                                            <a href="{% url 'noticias:detalle_noticia' n.pk %}">
                                                <h5 class="card-title">{{ n.titulo }}</h5>

                                            </a>
                                            <p class="card-text">Creado: {{n.creado}} - Ultima modificacion: {{n.modificado}}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="tab-pane fade" id="comments">
                                <!-- Contenido de la pestaña de comentarios -->
                                {% for comentario in comentarios_user %}
                                    <div class="card mb-3">
                                        <div class="card-body">
                                            <p class="card-text">Comentó: {{ comentario.contenido |slice:":100"}}...</p>
                                            <p class="card-text">Fecha:{{comentario.fecha_creacion}}</p>
        

                                            <a href="{% url 'noticias:detalle_noticia' comentario.noticia.pk %}">
                                                <p class="card-text">Post: {{comentario.noticia}}</p>

                                            </a>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
{% endblock contenido %}